name: Build
on:
  workflow_dispatch:
  push:
    branches:
      - '*'
    paths:
      - 'osm-api/**'
      - 'osm-tool/**'
      - 'osm-tool-test/**'
      - '.github/workflows/build.yml'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download PBF files
        uses: dawidd6/action-download-artifact@v9
        with:
          workflow: download-osm.yml
          workflow_conclusion: success
          event: push
          name: pbf-files

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - name: Restore
        run: |
            dotnet restore

      - name: Build
        run: |
            dotnet build

      - name: Test
        run: |
            dotnet test

      - name: Build database
        run: |
            cd osm-tool
            dotnet run ../greater-london.osm.pbf

      - name: Archive DB files
        uses: actions/upload-artifact@v4
        with:
          name: db-files
          path: |
            osm-tool/*.db

      - name: Download Godot files
        uses: dawidd6/action-download-artifact@v9
        with:
          workflow: build-godot.yml
          workflow_conclusion: success
          branch: main
          event: push
          path: godot-build/bin/

      - name: Create API Docker image
        run: |
            # remove godot prefix added by artifacts
            cd godot-build/bin
            for file in "godot-"*;
            do
              mv "$file" "${file#godot-}"
            done
            cd ../../osm-api
            ./build-docker.sh

      - name: Log into docker registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push API image
        run: |
            docker tag osm-api ghcr.io/richteaman/map-boy-api:latest
            docker push ghcr.io/richteaman/map-boy-api:latest
