name: Godot build
on:
  workflow_dispatch:
  push:
    branches:
      - '*'
    paths:
      - 'godot-build/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build
        run: |
            cd godot-build
            ./build.sh
      - name: Archive Godot binaries
        uses: actions/upload-artifact@v4
        with:
          name: dist-without-markdown
          path: |
            godot-build/bin/*
