name: Godot build
on:
  workflow_dispatch:
  push:
    branches:
      - '*'
    paths:
      - 'godot-build/**'

jobs:
  godot_build_matrix:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        build_name: [
          "linuxbsd-editor",
          "linuxbsd-template-release",
          "linuxbsd-template-debug",
          "windows-editor",
          "windows-template-release",
          "windows-template-debug",
          "web-release-no-threads",
          "web-debug-no-threads",
        ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build
        run: |
            cd godot-build
            ./build.sh ${{ matrix.build_name }}

      - name: Archive Godot ${{ matrix.build_name }} binary
        uses: actions/upload-artifact@v4
        with:
          name: godot-${{ matrix.build_name }}
          path: |
            godot-build/bin/${{ matrix.build_name }}/*
