name: Godot build
on:
  workflow_dispatch:
  push:
    branches:
      - '*'
    paths:
      - 'godot-build/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build
        run: |
            cd godot-build
            ./build.sh

      - name: Archive Godot linuxbsd binaries
        uses: actions/upload-artifact@v4
        with:
          name: godot-linuxbsd
          path: |
            godot-build/bin/linuxbsd/*
      - name: Archive Godot windows binaries
        uses: actions/upload-artifact@v4
        with:
          name: godot-windows
          path: |
            godot-build/bin/windows/*
      - name: Archive Godot web release no threads binaries
        uses: actions/upload-artifact@v4
        with:
          name: godot-web-release-no-threads
          path: |
            godot-build/bin/web-release-no-threads/*
      - name: Archive Godot web debug no threads binaries
        uses: actions/upload-artifact@v4
        with:
          name: godot-web-debug-no-threads
          path: |
            godot-build/bin/web-debug-no-threads/*
